import React from 'react';

const page = () => {
    return (
        <div>
            <main id="MainContent" className="content-for-layout focus-none px-20 md:px-80" role="main" tabIndex="-1">

                <div className="shopify-policy__container">
                    <div className="shopify-policy__title">
                        <h1>Terms of service</h1>
                    </div>

                    <div className="shopify-policy__body">
                        <div className="rte">

                            <p className="x_ContentPasted0"><span>These Revolution Mining&nbsp;<span className="mark90y30zik0">Terms</span>&nbsp;of Service govern your use of this website under the Revolution Mining name. Throughout the site and apps, the&nbsp;<span className="mark90y30zik0">terms</span>&nbsp;“we”, “us” and “our” refer to Revolution Mining. Revolution Mining offers this website, including all information, tools and services available from this site to you, the user, conditioned upon your acceptance of all&nbsp;<span className="mark90y30zik0">terms</span>, conditions, policies and notices stated here.</span></p>
                            <p className="x_ContentPasted0"><span>By visiting our site and purchasing something from us, you become a user of our “Services” and agree to be bound by the following&nbsp;<span className="mark90y30zik0">terms</span>&nbsp;and conditions (“<span className="mark90y30zik0">Terms</span>&nbsp;of Service”, “<span className="mark90y30zik0">Terms</span>” or “Agreement”), including those additional&nbsp;<span className="mark90y30zik0">terms</span>&nbsp;and conditions and policies referenced herein and/or available by hyperlink. These&nbsp;<span className="mark90y30zik0">Terms</span>&nbsp;of Service apply to all users of the site, including without limitation users who are browsers, vendors, customers, merchants, and/or contributors of content.</span></p>
                            <p className="x_ContentPasted0"><span>Please read these&nbsp;<span className="mark90y30zik0">Terms</span>&nbsp;of Service carefully before accessing or using our website. By accessing our site, you agree to be bound by these&nbsp;<span className="mark90y30zik0">Terms</span>&nbsp;of Service. If you do not agree to all the&nbsp;<span className="mark90y30zik0">terms</span>&nbsp;and conditions of this agreement, then you may not access the Services. If these&nbsp;<span className="mark90y30zik0">Terms</span>&nbsp;of Service are considered an offer, acceptance is expressly limited to these&nbsp;<span className="mark90y30zik0">Terms</span>&nbsp;of Service.</span></p>
                            <p className="x_ContentPasted0"><span>By agreeing to these&nbsp;<span className="mark90y30zik0">Terms</span>&nbsp;of Service, you represent that you are at least the age of majority in your state or province of residence, or that you are the age of majority in your state or province of residence and you have given us your consent to allow any of your minor dependents to use this site. If you are not of the age of majority in your state or province of residence, you may not use our Services without the consent of your parent, guardian, caretaker or other individual able to provide consent to your use of the Services.&nbsp;</span></p>
                            <p className="x_ContentPasted0"><span>Any new features or tools which are added to the current store shall also be subject to the&nbsp;<span className="mark90y30zik0">Terms</span>&nbsp;of Service. You can review the most current version of the&nbsp;<span className="mark90y30zik0">Terms</span>&nbsp;of Service at any time on this page. We reserve the right to update, change or replace any part of these&nbsp;<span className="mark90y30zik0">Terms</span>&nbsp;of Service by posting updates and/or changes to our website. It is your responsibility to check this page periodically for changes. We will notify you of any changes to these&nbsp;<span className="mark90y30zik0">Terms</span>&nbsp;by updating the “Last Updated” date at the top of these&nbsp;<span className="mark90y30zik0">Terms</span>&nbsp;of Service. Your continued use of or access to the website following the posting of any changes constitutes acceptance of those changes.</span></p>
                            <p className="x_ContentPasted0"><span>A breach or violation of any of the&nbsp;<span className="mark90y30zik0">Terms</span>&nbsp;will result in an immediate termination of your Services.</span></p>
                            <p className="x_ContentPasted0"><span>The headings used in this agreement are included for convenience only and will not limit or otherwise affect these&nbsp;<span className="mark90y30zik0">Terms</span>.</span></p>
                            <p className='py-4'><span><strong className="x_ContentPasted0">Section 1 – Online Store&nbsp;<span className="mark90y30zik0">Terms</span></strong></span></p>
                            <p className="x_ContentPasted0"><span>You may not use our products, including any product purchased through the Online Store, for any illegal or unauthorized purpose nor may you, in the use of the Service, violate any laws in your jurisdiction (including but not limited to copyright laws). A detailed list of prohibited uses of our Services, including uses related to the Online Store, is below in Section 12.</span></p>
                            <p className='py-4'><span><strong className="x_ContentPasted0">Section 2 – General Conditions</strong></span></p>
                            <p className="x_ContentPasted0"><span>We reserve the right to refuse service to anyone for any reason at any time.</span></p>
                            <p className="x_ContentPasted0"><span>You understand that your content (not including credit card information), may be transferred unencrypted and involve (a) transmissions over various networks; and (b) changes to conform and adapt to technical requirements of connecting networks or devices. Credit card information is always encrypted during transfer over networks.</span></p>
                            <p className="x_ContentPasted0"><span>You agree not to reproduce, duplicate, copy, sell, resell or exploit any portion of the Service, use of the Service, or access to the Service or any contact on the website through which the Services are provided, without our express written permission.</span></p>
                            <p className='py-4'><span><strong className="x_ContentPasted0">Section 3 – Accuracy, Completeness and Timeliness of Information</strong></span></p>
                            <p className="x_ContentPasted0"><span>We are not responsible if information made available on this site is not accurate, complete or current. Except where otherwise provided within the materials presented on the Services, the material on this site is provided for general information only and should not be relied upon or used as the sole basis for making decisions without consulting primary, more accurate, more complete or more timely sources of information. Any reliance on the material on this site is at your own risk.</span></p>
                            <p className="x_ContentPasted0"><span>This site may contain certain historical information. Historical information, by definition, is not current and is provided for your reference only. &nbsp;In particular, we may provide historical information regarding miner profitability that is based on information available to us. This information is not provided as financial advice and is not intended to provide any indication of future profitability. All use of such information is at your sole risk.</span></p>
                            <p className="x_ContentPasted0"><span>We reserve the right to modify the contents of this site at any time, but we have no obligation to update any information on our site. You agree that it is your responsibility to monitor changes to our site.</span></p>
                            <p className='py-4'><span><strong className="x_ContentPasted0">Section 4 – Modifications to the Service and Pricing</strong></span></p>
                            <p className="x_ContentPasted0"><span>Prices for our products are subject to change without notice.</span></p>
                            <p className="x_ContentPasted0"><span>We reserve the right at any time to modify or discontinue the Service (or any part or content thereof) without notice at any time.</span></p>
                            <p className="x_ContentPasted0"><span>We shall not be liable to you or to any third-party for any modification, price change, suspension, disruption or discontinuance of the Service.</span></p>
                            <p className='py-4'><span><strong className="x_ContentPasted0">Section 5 – Products or Services</strong></span></p>
                            <p className="x_ContentPasted0"><span>Certain products or services may be available exclusively online through the website. These products or services may have limited quantities and are subject to return or exchange only according to our Purchase Policy and Resale Policy.</span></p>
                            <p className="x_ContentPasted0"><span>We have made every effort to display as accurately as possible the colors and images of our products that appear at the store. We cannot guarantee that your computer monitor’s display of any color will be the same as it appears on our website.</span></p>
                            <p className="x_ContentPasted0"><span>We reserve the right, but are not obligated, to limit the sales of our products or Services to any person, geographic region or jurisdiction. We may exercise this right on a case-by-case basis. We reserve the right to limit the quantities of any products or services that we offer. All descriptions of products or product pricing are subject to change at any time without notice, at the sole discretion of us. We reserve the right to discontinue any product at any time. Any offer for any product or service made on this site is void where prohibited.</span></p>
                            <p className="x_ContentPasted0"><span>We reserve the right to refuse any order you place with us. We may, in our sole discretion, limit or cancel quantities purchased per person, per household or per order. These restrictions may include orders placed by or under the same customer account, the same credit card, and/or orders that use the same billing and/or shipping address. In the event that we make a change to or cancel an order, we will attempt to notify you by contacting the e-mail and/or billing address/phone number provided at the time the order was made. We reserve the right to limit or prohibit orders that, in our sole judgment, appear to be placed by dealers, resellers or distributors.</span></p>
                            <p className="x_ContentPasted0"><span>We may also, in the future, offer new Services and/or features through the website (including, the release of new tools and resources). Such new features and/or Services shall also be subject to these&nbsp;<span className="mark90y30zik0">Terms</span>&nbsp;of Service.</span></p>
                            <p className='py-4'><span><strong className="x_ContentPasted0">Section 6 – Accuracy of Billing and Account Information</strong></span></p>
                            <p className="x_ContentPasted0"><span>You agree to provide current, complete and accurate purchase and account information for all purchases made at our store. You agree to promptly update your account and other information, including your email address and credit card information, including the expiration date, so that we can complete your transactions and contact you as needed.</span></p>
                            <p className='py-4'><span><strong className="x_ContentPasted0">Section 7 – Optional Tools</strong></span></p>
                            <p className="x_ContentPasted0"><span>We may provide you with access to optional third-party tools over which we neither monitor nor have any control nor input.</span></p>
                            <p className="x_ContentPasted0"><span>You acknowledge and agree that we provide access to such tools “as is” and “as available” without any warranties, representations or conditions of any kind and without any endorsement. We shall have no liability whatsoever arising from or relating to your use of optional third-party tools.</span></p>
                            <p className="x_ContentPasted0"><span>Any use by you of optional tools offered through the site is entirely at your own risk and discretion and you should ensure that you are familiar with and approve of the&nbsp;<span className="mark90y30zik0">terms</span>&nbsp;on which tools are provided by the relevant third-party provider(s). We encourage you to become familiar with the policies of these third parties before using the optional third-party tools.</span></p>
                            <p className='py-4'><span><strong className="x_ContentPasted0">Section 8 – Third-Party Links</strong></span></p>
                            <p className="x_ContentPasted0"><span>Certain content, products and services available via our Service may include materials from third parties.</span></p>
                            <p className="x_ContentPasted0"><span>Third-party links on this site may direct you to third-party websites that are not affiliated with us. We are not responsible for examining or evaluating the content or accuracy of these sites, and you acknowledge that when you leave our site to visit these third-party sites, you do so at your own risk. We do not warrant and will not have any liability or responsibility for any third-party materials or websites, or for any other materials, products, or services of third parties.</span></p>
                            <p className="x_ContentPasted0"><span>We are not liable for any harm or damages related to the purchase or use of goods, services, resources, content, or any other transactions made in connection with any third-party websites. Please review carefully the third-party’s policies and practices and make sure you understand them before you engage in any transaction. Complaints, claims, concerns, or questions regarding third-party products should be directed to the third-party.</span></p>
                            <p className='py-4'><span><strong className="x_ContentPasted0">Section 9 – User Comments, Feedback and Other Submissions</strong></span></p>
                            <p className="x_ContentPasted0"><span>If, at our request, you send certain specific submissions (for example contest entries) or without a request from us you send creative ideas, suggestions, proposals, plans, or other materials, whether online, by email, by postal mail, or otherwise (collectively, “comments”), you agree that we may, at any time, without restriction, edit, copy, publish, distribute, translate and otherwise use in any medium any comments that you forward to us. We are and shall be under no obligation (1) to maintain any comments in confidence; (2) to pay compensation for any comments; or (3) to respond to any comments.</span></p>
                            <p className="x_ContentPasted0"><span>We may, but have no obligation to, monitor, edit or remove user content that we determine in our sole discretion is unlawful, offensive, threatening, libelous, defamatory, pornographic, obscene or otherwise objectionable or that violates any party’s intellectual property or these&nbsp;<span className="mark90y30zik0">Terms</span>&nbsp;of Service.</span></p>
                            <p className="x_ContentPasted0"><span>You agree that your comments and any content you post or submit to us or our website will not violate any right of any third-party, including copyright, trademark, privacy, personality or other personal or proprietary right. You further agree that your comments will not contain libelous or otherwise unlawful, abusive or obscene material, or contain any computer virus or other malware that could in any way affect the operation of the Service or any related website. You may not use a false e-mail address, pretend to be someone other than yourself, or otherwise mislead us or third-parties as to the origin of any comments. You are solely responsible for any comments you make or content you submit and its accuracy. We take no responsibility and assume no liability for any comments or content posted by you or any third-party.</span></p>
                            <p className='py-4'><span><strong className="x_ContentPasted0">Section 10 – Personal Information</strong></span></p>
                            <p className="x_ContentPasted0"><span>Our collection, use, sharing, retention and security of your personal information, is governed by our Privacy Policy available at&nbsp;</span><span>https://www.revolutionmining.io/pages/policy</span><span>. You may also send inquiries related to data privacy or security to us at:</span><span className="x_ContentPasted0">&nbsp;</span><span><u className="x_ContentPasted0">support@revolutionmining.io</u></span></p>
                            <p className='py-4'><span><strong className="x_ContentPasted0">Section 11 – Errors, Inaccuracies and Omissions</strong></span></p>
                            <p className="x_ContentPasted0"><span>Occasionally there may be information on our site or in the Service that contains typographical errors, inaccuracies or omissions that may relate to product descriptions, pricing, promotions, offers, product shipping charges, transit times and availability. We reserve the right to correct any errors, inaccuracies or omissions, and to change or update information or cancel orders without prior notice if any information in the Service or on any related website is inaccurate at any time (including after you have submitted your order).</span></p>
                            <p className="x_ContentPasted0"><span>We undertake no obligation to update, amend or clarify information in the Service or on any related website, including without limitation, pricing information, except as required by law. No specified update or refresh date applied in the Service or on any related website, should be taken to indicate that all information in the Service or on any related website has been modified or updated.</span></p>
                            <p className='py-4'><span><strong className="x_ContentPasted0">Section 12 – Prohibited Uses</strong></span></p>
                            <p className="x_ContentPasted0"><span>In addition to other prohibitions as set forth in the&nbsp;<span className="mark90y30zik0">Terms</span>&nbsp;of Service, you are prohibited from using the site or its content: (a) for any unlawful purpose; (b) to solicit others to perform or participate in any unlawful acts; (c) to violate any international, federal, provincial or state regulations, rules, laws, or local ordinances; (d) to infringe upon or violate our intellectual property rights or the intellectual property rights of others; (e) to harass, abuse, insult, harm, defame, slander, disparage, intimidate, or discriminate based on gender, sexual orientation, religion, ethnicity, race, age, national origin, or disability; (f) to submit false or misleading information; (g) to upload or transmit viruses or any other type of malicious code that will or may be used in any way that will affect the functionality or operation of the Service or of any related website, other websites, or the Internet; (h) to collect or track the personal information of others; (i) to spam, phish, pharm, pretext, spider, crawl, or scrape; (j) for any obscene purpose; or (k) to interfere with or circumvent the security features of the Service or any related website, other websites, or the Internet. We reserve the right to immediately terminate your use of the Service or any related website for violating any of the prohibited uses.</span></p>
                            <p className='py-4'><span><strong className="x_ContentPasted0">Section 13 – Disclaimer of Warranties; Limitation of Liability</strong></span></p>
                            <p className="x_ContentPasted0"><span>We do not guarantee, represent or warrant that your use of our Services will be uninterrupted, timely, secure or error-free.</span></p>
                            <p className="x_ContentPasted0"><span>We do not warrant that the results that may be obtained from the use of the Services will be accurate or reliable.</span></p>
                            <p className="x_ContentPasted0"><span>You agree that from time to time we may deactivate the Services for indefinite periods of time without notice to you. We also reserve the right to cancel the Services at any time.</span></p>
                            <p className="x_ContentPasted0"><span>You expressly agree that your use of, or inability to use, the Services is at your sole risk. The Services and all products and services delivered to you through the Services are (except as expressly stated by us) provided “as is” and “as available” for your use, without any representation, warranties or conditions of any kind, either express or implied, including all implied warranties or conditions of merchantability, merchantable quality, fitness for a particular purpose, durability, title, and non-infringement.</span></p>
                            <p className="x_ContentPasted0"><span>In no case shall Revolution Mining, our directors, officers, employees, affiliates, agents, contractors, interns, suppliers, service providers or licensors be liable for any injury, loss, claim, or any direct, indirect, incidental, punitive, special, or consequential damages of any kind, including, without limitation lost profits, lost revenue, lost savings, loss of data, replacement costs, or any similar damages, whether based in contract, tort (including negligence), strict liability or otherwise, arising from your use of the Services or any products procured using the Services, or for any other claim related in any way to your use of the Services or any product, including, but not limited to, any errors or omissions in any content, or any loss or damage of any kind incurred as a result of the use of the Services, or any content (or product) posted, transmitted, or otherwise made available via the Services, even if advised of their possibility. Because some states or jurisdictions do not allow the exclusion or the limitation of liability for consequential or incidental damages, in such states or jurisdictions, our liability shall be limited to the minimum required by law.</span></p>
                            <p className='py-4'><span><strong className="x_ContentPasted0">Section 14 – Indemnification</strong></span></p>
                            <p className="x_ContentPasted0"><span>You agree to indemnify, defend and hold harmless Revolution Mining and our parent, subsidiaries, affiliates, partners, officers, directors, agents, contractors, licensors, service providers, subcontractors, suppliers, interns and employees, harmless from any claim or demand, including reasonable attorneys’ fees, made by any third party due to or arising out of your breach, whether or not this breach was intentional, of these&nbsp;<span className="mark90y30zik0">Terms</span>&nbsp;of Service or the documents they incorporate by reference, or your violation of any law or the rights of a third party.</span></p>
                            <p className='py-4'><span><strong className="x_ContentPasted0">Section 15 – Severability</strong></span></p>
                            <p className="x_ContentPasted0"><span>In the event that any provision of these&nbsp;<span className="mark90y30zik0">Terms</span>&nbsp;of Service is determined to be unlawful, void or unenforceable, such provision shall nonetheless be enforceable to the fullest extent permitted by applicable law, and the unenforceable portion shall be deemed to be severed from these&nbsp;<span className="mark90y30zik0">Terms</span>&nbsp;of Service, and shall not affect the validity and enforceability of any other remaining provisions.</span></p>
                            <p className='py-4'><span><strong className="x_ContentPasted0">Section 16 – Termination</strong></span></p>
                            <p className="x_ContentPasted0"><span>The obligations and liabilities of the parties incurred prior to the termination date shall survive the termination of this agreement for all purposes.</span></p>
                            <p className="x_ContentPasted0"><span>These&nbsp;<span className="mark90y30zik0">Terms</span>&nbsp;of Service are effective unless and until terminated by either you or us. You may terminate these&nbsp;<span className="mark90y30zik0">Terms</span>&nbsp;of Service at any time by notifying us that you no longer wish to use our Services, or when you cease using our site. However, if you resume using our Services, the&nbsp;<span className="mark90y30zik0">Terms</span>&nbsp;of Service then in effect will apply to such usage.</span></p>
                            <p className="x_ContentPasted0"><span>If, in our sole judgment, you fail, or we suspect that you have failed, to comply with any term or provision of these&nbsp;<span className="mark90y30zik0">Terms</span>&nbsp;of Service, we may terminate this agreement at any time without prior notice and/or may deny you access to our Services (or any part thereof). You agree that you will remain liable for all obligations and amounts due up to and including the date of termination and/or denial of access to our Services.</span></p>
                            <p className='py-4'><span><strong className="x_ContentPasted0">Section 17 – Entire Agreement</strong></span></p>
                            <p className="x_ContentPasted0"><span>These&nbsp;<span className="mark90y30zik0">Terms</span>&nbsp;of Service and any policies or operating rules posted by us on this site or in respect to the service constitutes the entire agreement and understanding between you and Revolution Mining, and governs your use of the Services. These&nbsp;<span className="mark90y30zik0">Terms</span>&nbsp;of Service supersede any prior or contemporaneous agreements, communications and proposals, whether oral or written, between you and us (including, but not limited to, any prior versions of the&nbsp;<span className="mark90y30zik0">Terms</span>&nbsp;of Service).</span></p>
                            <p className="x_ContentPasted0"><span>Any ambiguities in the interpretation of these&nbsp;<span className="mark90y30zik0">Terms</span>&nbsp;of Service shall not be construed against the drafting party.</span></p>
                            <p className='py-4'><span><strong className="x_ContentPasted0">Section 18 – Governing Law &amp; Waiver</strong></span></p>
                            <p className="x_ContentPasted0"><span>Any dispute relating to the Services shall be adjudicated under the laws of the state of Texas without regard to Texas's choice of law provisions. Moreover, any legal dispute shall be brought in a Texas court having subject matter jurisdiction. You agree to waive any objection to the personal jurisdiction or to the venue in any Texas court having subject matter jurisdiction over the dispute. You also agree that in the event of a dispute, you will not bring any claim in any representative or class-action capacity or permit your claim to be adjudicated by another as your representative; rather, you agree that you will seek adjudication of only your own personal claim.</span></p>
                            <p className="x_ContentPasted0"><span>Our failure to exercise or enforce any right or provision of these&nbsp;<span className="mark90y30zik0">Terms</span>&nbsp;of Service shall not constitute a waiver of such right or provision.</span></p>
                            <p className='py-4'><span><strong className="x_ContentPasted0">Section 19 – Changes to&nbsp;<span className="mark90y30zik0">Terms</span>&nbsp;of Service</strong></span></p>
                            <p className="x_ContentPasted0"><span>You can review the most current version of the&nbsp;<span className="mark90y30zik0">Terms</span>&nbsp;of Service at any time at this page. The “Last Updated” date at the top of the&nbsp;<span className="mark90y30zik0">Terms</span>&nbsp;of Service reflects when the latest version of these&nbsp;<span className="mark90y30zik0">Terms</span>&nbsp;was posted to the website. Unless otherwise stated, changes to these&nbsp;<span className="mark90y30zik0">Terms</span>&nbsp;of Service are effective upon posting.</span></p>
                            <p className="x_ContentPasted0"><span>We reserve the right, at our sole discretion, to update, change or replace any part of these&nbsp;<span className="mark90y30zik0">Terms</span>&nbsp;of Service by posting updates and changes to our website. It is your responsibility to check our website periodically for changes. Your continued use of or access to our website or the Service following the posting of any changes to these&nbsp;<span className="mark90y30zik0">Terms</span>&nbsp;of Service constitutes acceptance of those changes.</span></p>
                            <p className='py-4'><span><strong className="x_ContentPasted0">Section 20 – Contact Information</strong></span></p>
                            <p className="x_ContentPasted0"><span>Questions about the&nbsp;<span className="mark90y30zik0">Terms</span>&nbsp;of Service should be sent to us at</span><span className="x_ContentPasted0">&nbsp;</span><span><u className="x_ContentPasted0">support@revolutionmining.io</u></span></p>
                        </div>
                    </div>
                </div>


            </main>
        </div>
    );
}

export default page;
